---

- name: Remove Netdata packages
  dnf:
    state: absent
    name:
      - "{{ netdata_repo_package }}"
      - "{{ netdata_agent_package }}"
  notify: dnf-clean-metadata

- name: Remove the remains
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
