---

- name: Remove Netdata packages
  dnf:
    state: absent
    name:
      - netdata
      - netdata-repo
      - netdata-repo-edge
  notify: dnf-clean-metadata

- name: Remove the remains
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
