---

# Not needed for Debian 11?
#- name: Install some essential packages
#   apt:
#     name: "{{ item }}"
#     update_cache: yes
#   loop:
#     - gpg
#     - debian-archive-keyring
#     - apt-transport-https

 - name: Install Netdata repo key.
   apt_key:
     url: https://packagecloud.io/netdata/netdata-repoconfig/gpgkey
     state: present
   become: True

 - name: Install netdata repo
   apt:
     deb: "{{ repo_uri }}"
