---
- package:
    name: uuid-runtime
    state: latest

- name: Install the package
  apt:
    name: netdata
    update_cache: yes
    state: latest
    # default_release:

- name: Start "{{ netdata_agent_service_name }}" service
  systemd:
    name: "{{ netdata_agent_service_name }}"
    state: started
    enabled: yes
    masked: no

