---
# defaults file for roles/install-netdata-agent
# Global
agent_user: netdata
agent_history: 3600
# Agent process scheduling policy
agent_policy: idle
# Agent OOM score
oom_score: 1000

# Web
owner: root
group: netdata
bind_to: localhost
